name: Angular CI/CD with Testing

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install Angular CLI globally
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # 4️⃣ Install project dependencies
      - name: Install dependencies
        run: npm install

      # 5️⃣ Run unit tests
      - name: Run Unit Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      # 6️⃣ Build Angular app (only if tests pass)
      - name: Build Angular app
        run: ng build --prod --base-href "https://kamal-danish.github.io/Angularcicd/"

      # 7️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/Angularcicd
